# Generated by Django 4.2.4 on 2023-11-02 10:24

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_nidhiprayas'),
    ]

    operations = [
        migrations.CreateModel(
            name='TideEIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('dateOfBirth', models.DateField()),
                ('address', models.TextField()),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('ideaDescription', models.TextField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer Not to Say', 'Prefer Not to Say')], default='None', max_length=20)),
                ('category', models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], default='None', max_length=10)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('conceptNote', models.FileField(upload_to='notes/')),
                ('aspectNote', models.FileField(upload_to='notes/')),
                ('previousRecipient', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('fullCommitment', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('noOtherFellowship', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('businessCommitment', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('notBeneficiary', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('registerPEP', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('whatsappNumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('instituteName', models.TextField()),
                ('applicantImage', models.ImageField(upload_to='applicantImage/')),
                ('aadharImage', models.ImageField(upload_to='applicantImage/')),
                ('panImage', models.ImageField(upload_to='applicantImage/')),
                ('teamMemberName', models.CharField(max_length=50)),
                ('teamMemberInstituteName', models.TextField()),
                ('teamMemberEducation', models.TextField()),
                ('teamMemberExperience', models.TextField()),
                ('projectTitle', models.CharField(max_length=100)),
                ('techStack', models.TextField()),
                ('projectVideo', models.FileField(upload_to='projectVideo/')),
                ('companyName', models.CharField(max_length=100)),
                ('incorporationDate', models.DateField()),
                ('companyDescription', models.TextField()),
                ('projectStatus', models.CharField(choices=[('Idea', 'Idea'), ('POC', 'POC'), ('Ready to commercialize', 'Ready to commercialize'), ('Prototype', 'PROTOTYPE'), ('Ready market product', 'Ready Market Product')], default='None', max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TideGrant',
            fields=[
                ('tideeir_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.tideeir')),
                ('panNumber', models.CharField(max_length=10, unique=True)),
                ('aadharNumber', models.CharField(max_length=12, unique=True)),
                ('applicantProfession', models.TextField()),
                ('annualIncome', models.CharField(max_length=10)),
                ('innovationBeneficiary', models.TextField()),
                ('prototypeCostDetails', models.TextField()),
                ('projectPeriod', models.TextField()),
                ('activities', models.TextField()),
                ('monitrableMilestones', models.TextField()),
                ('duration', models.TextField()),
                ('financialSupportStatus', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('forms.tideeir',),
        ),
    ]
